src/Castano.Web/Models/Login.cs
namespace Castano.Web.Models
{
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;

    public class Login
    {
        [Required]
        [Display(Name = "Usuario")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }

    public class RecaptchaResponse
    {
        [JsonProperty("success")]
        public bool Success { get; set; }
        [JsonProperty("error_codes")]
        public string[] ErrorCodes { get; set; }
    }
}

src/Castano.Web/Models/Pedido.cs
namespace Castano.Web.Models
{
    using Castano.Data.Pedido;
    using System;
    using System.Collections.Generic;

    public class ModelPedidoWeb
    {
        public string Cliente { get; set; }
        public string Salon { get; set; }
        public string Observaciones { get; set; }

        public string FechaHora { get; set; }
        public DateTime? Prueba { get; set; }
        public DateTime? Inicio { get; set; }
        public DateTime? Finalizacion { get; set; }

        public double TotalPedido { get; set; }
        public double Descuento { get; set; }
        public double Recargo { get; set; }
        public double TotalFinal { get; set; }

        public List<Equipo> EquiposRequeridos { get; set; }
    }
}

src/Castano.Web/Controllers/PedidoController.cs
namespace Castano.Web.Controllers
{
    using Castano.Data;
    using Castano.Data.Pedido;
    using Castano.Data.Identity;
    using Castano.Service;
    using Castano.Web.Models;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using Microsoft.Owin.Security;
    using Newtonsoft.Json;
    using System;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using System.Threading.Tasks;

    [Authorize]
    public class PedidoController : Controller
    {
        private readonly IEnvioMailService _envioMailService;
        private readonly ICastanoData _data;
        private readonly AppUserManager _userManager;

        public PedidoController(IEnvioMailService envioMailService, ICastanoData data, AppUserManager appUserManager)
        {
            this._envioMailService = envioMailService;
            this._data = data;
            this._userManager = appUserManager;
        }

        // GET: Pedido/
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated) return RedirectToAction("Login");
            return RedirectToAction("Create");
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            var pedido = new Pedido
            {
                Cliente = User.Identity.Name,
                FechaHora = DateTime.Now.ToString("dd/MM/yyyy HH:mm")
            };

            pedido.Equipos = _data.EquiposRepository.All.ToList();

            return View(pedido);
        }

        [HttpPost]
        public JsonResult Create(ModelPedidoWeb pedidoWeb)
        {
            var pathEmail = Server.MapPath("~/Views/EmailTemplate/MailPedido.html");
            var pedidoParaEnviar = new Pedido
            {
                FechaHora = pedidoWeb.FechaHora,
                Cliente = pedidoWeb.Cliente,
                Salon = pedidoWeb.Salon,
                Prueba = pedidoWeb.Prueba,
                Inicio = pedidoWeb.Inicio,
                Finalizacion = pedidoWeb.Finalizacion,
                Equipos = pedidoWeb.EquiposRequeridos,
                Observaciones = pedidoWeb.Observaciones
            };

            //Elementos auxiliares
            var descuento = pedidoWeb.Descuento;
            var recargo = pedidoWeb.Recargo;

            if (pedidoParaEnviar.IsValid())
            {
                try
                {
                    var result = _envioMailService.SendMail(pedidoParaEnviar, descuento, recargo, pathEmail);

                    if (result.IsValid)
                    {
                        return new JsonResult
                        {
                            Data = new
                            {
                                fechaHora = DateTime.Now.ToString("dd/MM/yyyy HH:mm"),
                                envioCorrecto = true,
                                msg = "Su pedido se envió éxitosamente. Estaremos comunicándonos con usted a la brevedad."
                            },
                            JsonRequestBehavior = JsonRequestBehavior.AllowGet
                        };
                    }

                    return new JsonResult
                    {
                        Data = new
                        {
                            fechaHora = DateTime.Now.ToString("dd/MM/yyyy HH:mm"),
                            envioCorrecto = false,
                            msg = $"Su pedido no ha podido enviarse. Se ha producido un error. {result.MensajeErrores}"
                        },
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
                catch (System.Exception exc)
                {
                    return new JsonResult 
                    { 
                        Data = new 
                        { 
                            fechaHora = DateTime.Now.ToString("dd/MM/yyyy HH:mm"), 
                            envioCorrecto = false, 
                            msg = $"Su pedido no ha podido enviarse. Se ha producido un error. {exc.Message}" 
                        }, 
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet 
                    };
                }
            }

            return new JsonResult 
            { 
                Data = new 
                { 
                    fechaHora = DateTime.Now.ToString("dd/MM/yyyy HH:mm"), 
                    envioCorrecto = false, 
                    msg = "Su pedido no ha podido enviarse. El formulario que está intentando enviar no es válido, por favor corrija y vuelva a intentarlo." 
                }, 
                JsonRequestBehavior = JsonRequestBehavior.AllowGet 
            };
        }

        // GET: Pedido/Login
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        // POST: Pedido/Login
        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Login(Login login)
        {
            var secret = "6LfBQOIUAAAAAODnw5bhLcW7QO3nvL9EuZ5S27qC";
            var g_captcha = this.Request.Form["g-recaptcha-response"];

            var response = new WebClient().DownloadString(string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secret, g_captcha));
            var recaptchaResponse = JsonConvert.DeserializeObject<RecaptchaResponse>(response);

            if (recaptchaResponse.Success)
            {
                var user = await _userManager.FindAsync(login.UserName, login.Password);

                if (user != null)
                {
                    AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                    var identity = await _userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                    AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, identity);

                    return RedirectToAction("Create", new { cliente = login.UserName });
                }
            }

            ViewBag.Error = "Usuario o contraseña incorrectos.";
            return View(login);
        }

        // GET: /Pedido/LogOff
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

    }
}

src/Castano.Web/Views/Pedido/Login.cshtml
@model Castano.Web.Models.Login
@{
    ViewBag.Title = "Login Pedido CASTANO & asociados";
}
<div class="body">
    <!-- Navigation -->
    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="@Url.Action("Index", "Home")">
                    <img alt="castano&asociados" src="~/img/logo.jpg" style="max-width: 250px" />
                </a>
            </div>
        </nav>
    </div>
    <section>
        <div class="jumbotron">
            @if (ViewBag.Error != null)
            {
                <div class="alert alert-dismissible fade show alert-danger" role="alert" id="AlertMensaje">
                    <strong id="AlertTitle">Error!</strong> @ViewBag.Error
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            <div class="container mt-5 mb-5">
                <div class="well no-padding">
                    @using (Html.BeginForm("Login", "Pedido", null, FormMethod.Post, new { id = "LoginForm", @class = "animated fadeInDown" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="fas fa-user"></i>
                                    </span>
                                </div>
                                @Html.TextBoxFor(m => m.UserName, new { placeholder = "Usuario", @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="fas fa-lock"></i>
                                    </span>
                                </div>
                                @Html.PasswordFor(m => m.Password, new { placeholder = "Password", @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="g-recaptcha" data-sitekey="6LfBQOIUAAAAAKvtRuZM54-NOigyvZWyd2YGGY2g"></div>
                        </div>

                        <button type="submit" class="btn btn-primary" id="btnSubmit">Ingresar</button>
                    }
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/bootstrap-validator")
    @Scripts.Render("~/bundles/jquery-blockUI")
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#LoginForm").submit(function () {
                $.blockUI({ message: '<h3>Aguarde un momento por favor...</h3>' });
            });
        });
    </script>
}