src/Castano.Web/Controllers/EventoController.cs
namespace Castano.Web.Controllers
{
    using Castano.Service;
    using Castano.Web.Models;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web.Mvc;

    public class EventoController : Controller
    {
        private readonly IEventoService _eventoService;
        public EventoController(IEventoService eventoService)
        {
            this._eventoService = eventoService;
        }
        // GET: Evento
        public ActionResult Index()
        {
            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Eventos", "eventos.json");
            var eventos = _eventoService.ListEventos(path);
            return View(eventos);
        }

        // GET: Evento/UploadFile
        public ActionResult UploadFile()
        {
            return View();
        }

        // POST: Evento/UploadFile
        [HttpPost]
        public ActionResult UploadFile(string Password)
        {
            if(Password != "CAST2458") return HttpNotFound();
            
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                using (StreamReader memStream = new StreamReader(file.InputStream))
                {
                    var content = memStream.ReadToEnd();
                    //
                    if (string.IsNullOrEmpty(content)) throw new ApplicationException("El archivo está vacio.");

                    var filas = content.Trim().Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries).Skip(1);
                    var numeroFila = 2;
                    List<Evento> eventos = new List<Evento>();
                    foreach (var fila in filas)
                    {
                        var evento = new Evento(fila, numeroFila);

                        eventos.Add(evento);

                        numeroFila++;
                    }

                    ViewBag.Success = "Se agregaron los eventos.";
                    return View(eventos);
                }
            }
            return View();
        }
    }
}

src/Castano.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Castano.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Castano.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Castano.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Castano.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "CASTANO & asociados";
}
<div class="body">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <img alt="castano&asociados" src="~/img/logo.jpg" style="max-width: 250px" />
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#quienessomos">Quienes Somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#servicios">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#eventos">Eventos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contacto">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!--Encabezado-->
    <header class="masthead text-center text-white d-flex">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">
                        <strong>CÁSTANO</strong>
                    </h1>
                    <h1>
                        &amp; asociados
                    </h1>
                    <hr />
                </div>
                <div class="col-lg-8 mx-auto">
                    <h5 class="text-faded mb-5">
                        Más de 40 años proyectando el futuro
                    </h5>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#quienessomos">Quiénes somos</a>
                </div>
            </div>
        </div>
    </header>
    <!--Quienes somos-->
    <section class="bg-primary" id="quienessomos">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto text-center">
                    <h2 class="section-heading text-white">Quiénes somos</h2>
                    <hr class="light my-4">
                    <p class="text-faded mb-4">
                        CASTANO & asociados es una empresa dedicada enteramente al desarrollo de servicios integrales de imagen y sonido,
                        iniciada por Francisco J. Cástano en el año 1976. La cuidadosa atención de nuestro personal capacitado y la permanente
                        actualización de nuestro equipamiento, nos permite garantizar resultados de óptima calidad, asumiendo un compromiso
                        total con el éxito de cada proyecto.
                    </p>
                    <a class="btn btn-light btn-xl js-scroll-trigger" href="#servicios">Servicios</a>
                </div>
            </div>
        </div>
    </section>
    <!--Servicios-->
    <section id="servicios">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mx-auto text-center">
                    <h2 class="section-heading text-primary">Nuestros Servicios</h2>
                    <hr class="my-4">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-microphone text-primary mb-3 sr-icon-1"></i>
                                <h3 class="mb-3">Sonido Profesional</h3>
                                <p class="text-muted mb-0">
                                    Contamos con una amplia gama que va desde un sonido básico hasta un sistema de sonido de alto impacto
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-video text-primary mb-3 sr-icon-2"></i>
                                <h3 class="mb-3">Proyección</h3>
                                <p class="text-muted mb-0">
                                    Nuestro servicio de proyección cuenta con equipos de última generación
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-broadcast-tower text-primary mb-3 sr-icon-3"></i>
                                <h3 class="mb-3">Traducción Simultánea</h3>
                                <p class="text-muted mb-0">
                                    Brindamos el confort necesario a los traductores para que lleven adelante su labor de forma óptima
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 text-center">
                            <div class="service-box mt-5 mx-auto">
                                <i class="fas fa-4x fa-users text-primary mb-3 sr-icon-4"></i>
                                <h3 class="mb-3">Personal Idóneo</h3>
                                <p class="text-muted mb-0">
                                    Nuestro personal cuenta con los conocimientos necesarios para cumplir con su deber
                                </p>
                            </div>
                        </div>
                    </div>
                    <p></p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#eventos">Eventos</a>
                </div>
            </div>
        </div>
    </section>
    <!--Eventos-->
    <section class="bg-primary" id="eventos">
        <div class="container-fluid text-center p-0">
            <h2 class="section-heading text-white">Nuestros Eventos</h2>
            <hr class="light my-4">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active" style="background-image: url('img/carousel01.jpg')">
                        <div class="carousel-caption d-none d-sm-block carousel-text">
                            <h3>IDEA</h3>
                            <h5>26 de julio de 2016 / Salón Francés, RESTAURANT MERCURIO</h5>
                            <p>IDEA Centro realiza la 3er. Cena Foro del Ciclo 2016.</p>
                        </div>
                    </div>
                    <div class="carousel-item" style="background-image: url('img/carousel02.jpg')">
                        <div class="carousel-caption d-none d-sm-block carousel-text">
                            <h3>GRUPO BLUM</h3>
                            <h5>24 de julio de 2015 / Salón Barcelona, RIVIERA PALACE HOTEL</h5>
                            <p>Almuerzo "Día del Amigo" con que el GRUPO BLUM agasaja a sus clientes frecuentes.</p>
                        </div>
                    </div>
                    <div class="carousel-item" style="background-image: url('img/carousel03.jpg')">
                        <div class="carousel-caption d-none d-sm-block carousel-text">
                            <h3>BIOTOSCANA</h3>
                            <h5>22 de julio de 2016 / Salón Lamorak, HOLIDAY INN</h5>
                            <p>Seminario "Actualización en HAP 2016".</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Prev</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <p></p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="@Url.Action("Index", "Evento")">Más Eventos</a>
        </div>
    </section>
</div>